-- =============================================================================
-- PAR: 99 - Teardown (standalone cleanup)
-- Safe to run at any time — drops all PAR demo objects
-- =============================================================================

USE ROLE ACCOUNTADMIN;

-- Cortex Agent
ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
  REMOVE AGENT CUSTOMER_DEMOS.PAR.PAR_AGENT;
DROP AGENT IF EXISTS CUSTOMER_DEMOS.PAR.PAR_AGENT;

-- Cortex Search Services
DROP CORTEX SEARCH SERVICE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_PLAYBOOK_SEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_KB_SEARCH;

-- Notification integration
DROP NOTIFICATION INTEGRATION IF EXISTS PAR_EMAIL_INTEGRATION;

-- Procedures
DROP PROCEDURE IF EXISTS CUSTOMER_DEMOS.PAR.SEND_EMAIL(VARCHAR, VARCHAR, VARCHAR);

-- Semantic View
DROP SEMANTIC VIEW IF EXISTS CUSTOMER_DEMOS.PAR.PAR_SEMANTIC_VIEW;

-- Analytical Views
DROP VIEW IF EXISTS CUSTOMER_DEMOS.PAR.VW_CUSTOMER_HEALTH_360;
DROP VIEW IF EXISTS CUSTOMER_DEMOS.PAR.VW_MESSAGE_DELIVERY;
DROP VIEW IF EXISTS CUSTOMER_DEMOS.PAR.VW_ATTENDANCE_IMPACT;
DROP VIEW IF EXISTS CUSTOMER_DEMOS.PAR.VW_REVENUE_DASHBOARD;
DROP VIEW IF EXISTS CUSTOMER_DEMOS.PAR.VW_SUPPORT_ANALYTICS;

-- Search backing tables
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_PLAYBOOK_DOCS;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_KB_DOCS;

-- Stage
DROP STAGE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_DOCS_STAGE;

-- Fact and dimension tables (child tables first)
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_MESSAGES;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_ATTENDANCE_EVENTS;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_SUPPORT_TICKETS;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_FEATURE_USAGE;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_SUBSCRIPTIONS;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_CONTACTS;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_DISTRICTS;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_PRODUCT_MODULES;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_DISTRICT_TIERS;
DROP TABLE IF EXISTS CUSTOMER_DEMOS.PAR.PAR_STATES;

-- Schema and Warehouse
DROP SCHEMA    IF EXISTS CUSTOMER_DEMOS.PAR;
DROP WAREHOUSE IF EXISTS PAR_WH;
